### ISSUE TITLE
List::next() does not seem to work

### ISSUE THREAD

**Issue by dthul** [wyyerd/stripe-rs#105]
It seems like `List::next()` constructs an invalid URL.

When I try to get all active subscriptions using `Subscriptions::list`, the first request hits `https://api.stripe.com/v1/subscriptions` and succeeds. When I try to get the next page of results using `List::next`, the URL becomes `https://api.stripe.com/v1/ubscriptions` (note the missing "s").
The culprit seems to be the combination of `Client::url`:
https://github.com/wyyerd/stripe-rs/blob/0ed6d736c14455ea8a4488c383d874897c711097/src/client.rs#L124
which removes the first character from the path (because it expects the path to start with a slash), but `List::get_next`:
https://github.com/wyyerd/stripe-rs/blob/0ed6d736c14455ea8a4488c383d874897c711097/src/params.rs#L169
already removed the slash.

**Comment by stearnsc** [comment]
resolved by https://github.com/wyyerd/stripe-rs/pull/120
