### ISSUE TITLE
Update to the latest version of the Stripe API (v2019-12-03 as of 03/02/2020)

### ISSUE THREAD

**Issue by kestred** [wyyerd/stripe-rs#122]
Many changes have come since the last time we pulled the `openapi/spec3.json` (`2019-09-09`).

Notably, Stripe has changed many of their _documentation_ patterns, and we'll need to update our doc-comment generator to handle the new documentation format(s).

**Comment by ruseinov** [comment]
@kestred are there any plans to work on this? Or maybe there's a WIP branch somewhere?
Unfortunately Stipe does not allow to downgrade the API version for webhooks, which means that some of the functionality for new Stripe accounts is broken, including ```invoice.payment_succeeded```. 
I'm going to try and fix the events I absolutely need, but of course it would be better to be able to generate the code. If there is any work already done in that direction - I'd appreciate it if it got shared for me to build upon. I will be happy to contribute the end result.

**Comment by ruseinov** [comment]
This seems to support the openapi v3 spec: https://github.com/OpenAPITools/openapi-generator, but the output is not 100% compatible.

**Comment by kestred** [comment]
Implemented on master, for 0.13.0

**Comment by ruseinov** [comment]
Thanks a lot, I have temporarily specified last commit in master as a dependency, it works beautifully now. I'd fixed some of the events I needed manually, but that's much better!
