### ISSUE TITLE
price.rs file is missing at crates.io

### ISSUE THREAD

**Issue by lennartkloock** [wyyerd/stripe-rs#148]
The file(src/resources/price.rs) is just missing and I can't use the structs and functions in my project. I really don't know why?!
[https://docs.rs/crate/stripe-rust/0.12.3/source/src/resources/](https://docs.rs/crate/stripe-rust/0.12.3/source/src/resources/)

**Comment by drusellers** [comment]
Same here. I'm wondering if the failing build isn't helping?

**Comment by PockelHockel** [comment]
I solved it by doing the requests to the stripe servers myself. (With https://crates.io/crates/reqwest)

**Comment by PockelHockel** [comment]
This crate seems to be not that well maintained at all

**Comment by arlyon** [comment]
Closing now that async-stripe in the de-facto successor
