### ISSUE TITLE
Support for alternative 'runtimes'

### ISSUE THREAD

**Issue by arlyon** [wyyerd/stripe-rs#150]
Hey! I am using `async_std` and would like to avoid having to use any adaptors for tokio. This is a bit of a pain point in the ecosystem however there is inspiration to be taken from `sqlx` which exposes 'runtimes' as features. As of now, we have three runtimes: `runtime-tokio-hyper-tls`, `runtime-tokio-hyper-rustls`, and `blocking`.

In theory, adding a new runtime is as easy as adding a new feature (such as `runtime-async-std-surf-rustls`) and creating an appropriate file in the `clients` module.

Is this something that would be interesting for the project?

**Comment by kennetpostigo** [comment]
Hi, any chance there has been progress on this front?

**Comment by arlyon** [comment]
Closing now that async-stripe in the de-facto successor
