### ISSUE TITLE
0.12.3 does not compile (hmac-crypto got yanked)

### ISSUE THREAD

**Issue by roy-ganz** [wyyerd/stripe-rs#186]
Version 0.12.3 depends on hmac = 0.6.
That causes troubles, because the depended crate `hmac-crypto` `0.6` got yanked.
Please consider upgrading the `hmac`.
```
error: failed to select a version for the requirement `crypto-mac = "^0.6"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `hmac v0.6.0`
    ... which is depended on by `stripe-rust v0.12.3`
```

As a workaround in `cargo.toml` this patch pulls in the yanked dependency:
```
[patch.crates-io]
crypto-mac = {git="https://github.com/RustCrypto/traits" , tag="crypto-mac-v0.6.2"}
```

**Comment by seanpianka** [comment]
Please pull the latest from GitHub using:
```rust
[dependencies]
stripe-rust = { git = "https://github.com/wyyerd/stripe-rs.git" }
```

**Comment by fancywriter** [comment]
@seanpianka any plans to make a release to include this change? It's more than 9 months since then...

**Comment by arlyon** [comment]
We don't have access to making releases. You will need to get ahold of someone at wyyerd (@kestred )
