### ISSUE TITLE
New contributors

### ISSUE THREAD

**Issue by imalsogreg** [wyyerd/stripe-rs#196]
Hello! We have been using `stripe-rs` at work. We really love the library, in addition to depending on it, so we would like to support the library in whatever way is most useful.

Is there a particular area where we could contribute?

The people who would we working on this are me, @jbhsieh and @ada-hall

**Comment by seanpianka** [comment]
Hello all 👋 This would be a very welcome effort by many of the users of this library!

For the highest impact work on this project, check out the 0.13 release's issue. It contains a number of important tasks that are semi-planned to be completed before the next minor version release.

One important notice is that one of our maintainers (@arlyon) has started a fork called async-stripe. It has received a number of major improvements which at present have not been merged back into upstream. In terms of future feature development, starting from this more actively-developed base is something to consider.

Alternatively, if there were three people actively working on upstreaming his changes to this project, that would be a path to benefit the greatest number of users of this crate.

**Comment by kushwahashiv** [comment]
@imalsogreg @arlyon I'm also a bit confused which one to use as I'm upgrading `stripe-rs` but seems this crate is not up to date and lagging dependencies. Now my worry is what if `async-stripe` have completely different names of enums, structs etc. I hope that's not the case. can you please confirm  @arlyon.

thanks
/shiv
