### ISSUE TITLE
Problem with nested elements 

### ISSUE THREAD

**Issue by barlindhaug** [wyyerd/stripe-rs#22]
When I try to post something to stripe with nested elements, for example metadata fields, I get the following error.

`error_cause: caused by: error communicating with stripe: unsupported value`

I did a `println` on the `request` variable inside the `post` function and it looks like this:

`RequestBuilder { client: Client, request: Err(Inner { kind: UrlEncoded(Custom("unsupported value")), url: None }) }`

I think it may be related to this reqwest error: https://github.com/seanmonstar/reqwest/issues/274 Do you have any suggestions for a workaround untill reqwest hopefully migrates from serde to serde_qs?

**Comment by kestred** [comment]
I'll publish the fix later today after review + pipeline passes. There are added tests, but certainly if you'd like to test it out with your real data its always appreciated 😁 .

**Comment by barlindhaug** [comment]
I just tested this out, and it works perfectly.
Thanks for the fast response 👍 😄
