### ISSUE TITLE
PaymentIntents implementation

### ISSUE THREAD

**Issue by serejkaaa512** [wyyerd/stripe-rs#25]
It looks like PaymentIntents will be used in near future for Stripe SCA integration. Are there any plans for implementing it?

**Comment by serejkaaa512** [comment]
Added:
https://github.com/wyyerd/stripe-rs/pull/29

**Comment by kestred** [comment]
I hadn't seen it before.

But yeah, definitely lets get it `PaymentIntents` and the whole `SCA` workflow implemented!

> **Side Note:** Once we finish implementing the entire Stripe API, maybe we can _amicably coerce_
> the Stripe developers into making commits to the library 🤐😆.

**Comment by kestred** [comment]
MR #29 has been merged in and will be included in the next publish.

**Comment by kestred** [comment]
Payment intents has been published to __crates.io__ as part of `v0.8.0`.
