### ISSUE TITLE
Payout and Refunds fns implementation

### ISSUE THREAD

**Issue by serejkaaa512** [wyyerd/stripe-rs#26]
Subj is missing

**Comment by serejkaaa512** [comment]
Second one:
https://github.com/wyyerd/stripe-rs/pull/27

**Comment by serejkaaa512** [comment]
First one:
https://github.com/wyyerd/stripe-rs/pull/28

**Comment by kestred** [comment]
Implemented in your #27 and #28.

**Comment by kestred** [comment]
These implementations have been published to __crates.io__ as part of `v0.8.0`.
