### ISSUE TITLE
Replace `&str` and `String` with `enums when fields have a limited set of variants

### ISSUE THREAD

**Issue by kestred** [wyyerd/stripe-rs#3]
If there is a reasonable expectation Stripe may choose to add more values in the future (i.e. probably always), enums should also contain a variant:

```rust
    #[serde(other)] Other(String),
```

### Fields to be updated
Please reply to this issue if you see another field which should be an enum,and I will add it to the task list.

 * [x] A `ChargeStatus` for the `status` field on `Charge` (https://stripe.com/docs/api#charge_object)
 * [x] Many fields on the `ChargeOutcome` object
 * [x] The `address_zip_check`, `address_line1_check`, `cvc_check`, `funding` and `brand`fields on `Card` (https://stripe.com/docs/api#card_object)
 * [x] Many fields on the `Source` object and sub-objects

 * [ ] __(Likely More)__ _I'll get someone to do an audit before some 0.6.0_

**Comment by andreevlex** [comment]
Need change values and update objects:
ChargeOutcome
Charge

**Comment by andreevlex** [comment]
Invalid
```rust 
#[serde(other)] Other(String),
```

Valid only this variant 

```rust
#[serde(other)]
Other,
```

**Comment by kestred** [comment]
This is a continuous process (one that often results in breaking, but _good_ changes), but it is mostly complete!  Will want to revisit before releasing any "stable" 1.0.0 release, but I'm closing the issue for now ^_^.
