### ISSUE TITLE
Eq/parialEq missing on PaymentIntentStatus

### ISSUE THREAD

**Issue by Yatekii** [wyyerd/stripe-rs#71]
Why did you remove `Eq` and `PartialEq` from `PaymentIntentStatus` in recent versions?

**Comment by kestred** [comment]
This looks like a mistake that was made when `PaymentIntentStatus` was switched to become autogenerated.  I'll go ahead and fix the generator to derive the right traits.

**Comment by kestred** [comment]
This was implemented whenever `v0.10.4` was released
