### ISSUE TITLE
Support `Stripe-Version` header

### ISSUE THREAD

**Issue by ThouCheese** [wyyerd/stripe-rs#76]
To test the new Stripe API version for our software I need to set the `Stripe-Version` header. Currently, the only supported headers seem to be `Stripe-Account` and `Client-Id`. This makes it impossible to use a different version on the test suite than on the production server.

**Comment by ThouCheese** [comment]
I have create a [pull request](https://github.com/wyyerd/stripe-rs/pull/77) to close this issue

**Comment by kestred** [comment]
Merged in.  I'll publish to crates.io soon; probably early next week.

**Comment by ThouCheese** [comment]
Great to hear!

**Comment by kestred** [comment]
This was released as part of [v0.11.0](https://github.com/wyyerd/stripe-rs/blob/v0.11.0/CHANGELOG.md)
