### ISSUE TITLE
Parse error when balance is negative

### ISSUE THREAD

**Issue by phayes** [wyyerd/stripe-rs#80]
When a customer has a negative value in their `balance` field, fetching the customer results in a parse-error. This is because `balance` is `u64` but it *should* be `i64`. 

I've created a PR against the stripe openapi specification to fix this: https://github.com/stripe/openapi/pull/50

**Comment by phayes** [comment]
I think this might be an error in the open-api implementation here since according to the spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types)

The spec says: "integer as a type is also supported and is defined as a JSON number without a fraction or exponent part".   This means that a integer without a "format" should be interpreted as an i64.

**Comment by phayes** [comment]
A fix is here: https://github.com/wyyerd/stripe-rs/pull/81

**Comment by ambaldwin21** [comment]
PR merged.
