### ISSUE TITLE
Incorrect handling for nullable booleans in codegen

### ISSUE THREAD

**Issue by gperinazzo** [wyyerd/stripe-rs#84]
The openapi codegen currently handles non-required booleans using `#[serde(default)]`. This works to set the value to false if the field is missing in the input json, but if the attribute is nullable deserialization will fail if it finds a null.

The assumption seems to be documented in [line 1392 of the codegen source](https://github.com/wyyerd/stripe-rs/blob/master/openapi/src/main.rs#L1392)

I've written a small example:
```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct NoAttribute {
    field: bool,
}

#[derive(Debug, Deserialize)]
struct DefaultAttribute {
    #[serde(default)]
    field: bool,
}

#[derive(Debug, Deserialize)]
struct OptionalField {
    field: Option<bool>,
}

fn main() {
    let json = r#"{"field":null}"#;

    dbg!(serde_json::from_str::<NoAttribute>(json));
    dbg!(serde_json::from_str::<DefaultAttribute>(json));
    dbg!(serde_json::from_str::<OptionalField>(json));
}
```
Which outputs:
```
[src/main.rs:22] serde_json::from_str::<NoAttribute>(json) = Err(
    Error("invalid type: null, expected a boolean", line: 1, column: 13),
)
[src/main.rs:23] serde_json::from_str::<DefaultAttribute>(json) = Err(
    Error("invalid type: null, expected a boolean", line: 1, column: 13),
)
[src/main.rs:24] serde_json::from_str::<OptionalField>(json) = Ok(
    OptionalField {
        field: None,
    },
)
```

I had this issue trying to receive a `product.created` event where `shippable` seems to be set to null.

**Comment by kestred** [comment]
I've made a fix for this issue in https://github.com/wyyerd/stripe-rs/pull/93.

Thanks for submitting the issue.

**Comment by kestred** [comment]
This change was made in the "major" [v0.11.0 release](https://github.com/wyyerd/stripe-rs/blob/v0.11.0/CHANGELOG.md)
