### ISSUE TITLE
Issue with ids

### ISSUE THREAD

**Issue by FGRibreau** [wyyerd/stripe-rs#92]
Hello !

First thing first thanks a lot to maintain stripe-rs.

Since stripe-rs moved to v0.10 I can't find a way to use it correctly.

Before, this was working:

```
let mut param = ListInvoices::new();
param.customer = Some("cus_FmelnPfSBAKAG2");
```

and now I got:

```
  --> src/handlers/customers/invoices/mod.rs:10:27
   |
10 |     param.customer = Some("cus_FmelnPfSBAKAG2");
   |                           ^^^^^^^^^^^^^^^^^^^^ expected struct `stripe::CustomerId`, found reference
   |
   = note: expected type `stripe::CustomerId`
              found type `&'static str`
```

Looking at the changes, CustomerId was introduced, it's a struct (tuple) generated by this macro

https://github.com/wyyerd/stripe-rs/blob/master/src/ids.rs#L91-L200

`pub struct $struct_name(smol_str::SmolStr);`

I've tried multiple things:

```
error[E0277]: the trait bound `stripe::CustomerId: std::convert::From<&str>` is not satisfied
  --> src/handlers/customers/invoices/mod.rs:10:48
   |
10 |     param.customer = Some("cus_FmelnPfSBAKAG2".into());
   |                                                ^^^^ the trait `std::convert::From<&str>` is not implemented for `stripe::CustomerId`
   |
   = note: required because of the requirements on the impl of `std::convert::Into<stripe::CustomerId>` for `&str`
```

this should work:

```
error[E0423]: expected function, found struct `stripe::CustomerId`
  --> src/handlers/customers/invoices/mod.rs:10:27
   |
10 |     param.customer = Some(stripe::CustomerId(SmolStr::from("cus_FmelnPfSBAKAG2")));
   |                           ^^^^^^^^^^^^^^^^^^ did you mean `stripe::CustomerId { /* fields */ }`?
```

but since the first field of the tuple is private so I cannot use `stripe::CustomerId { 0:SmolStr::from("cus_FmelnPfSBAKAG2") }` (which seems verbose and wrong indeed).

`Some("cus_FmelnPfSBAKAG2".to_string())` does not work either:

```
error[E0308]: mismatched types
  --> src/handlers/customers/invoices/mod.rs:10:27
   |
10 |     param.customer = Some("cus_FmelnPfSBAKAG2".to_string());
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `stripe::CustomerId`, found struct `std::string::String`
   |
   = note: expected type `stripe::CustomerId`
              found type `std::string::String`
```

**Comment by kestred** [comment]
Hi.

If you've got a raw string:

 - If you are deserializing it from something else, the `Id` types support `serde` and can be serialized and deserialized directly.
 - If you need to use a raw string, you can convert it to an `Id` type with _e.g._ `"cus_FmelnPfSBAKAG2".parse()?`.

**Comment by FGRibreau** [comment]
Thanks!
