### ISSUE TITLE
Update to `std::future::Future`

### ISSUE THREAD

**Issue by JohnDoneth** [wyyerd/stripe-rs#97]
Now that [reqwest-0.10.0-alpha.1](https://github.com/seanmonstar/reqwest) is out, it seems like a good time to consider updating to it and the new `std::future::Future` ecosystem. Rust will include support for async-await on stable in 1.39 on November 7th.

**Comment by kestred** [comment]
#100 has been merged.  I'll publish a `0.12.0` soon (hopefully today).
